import type { IconType } from "react-icons";
import {
  SiAxios,
  SiDocker,
  SiExpo,
  SiExpress,
  SiFastapi,
  SiGooglegemini,
  SiJsonwebtokens,
  SiJupyter,
  SiPydantic,
  SiPytest,
  SiSqlalchemy,
  SiMobx,
  SiMocha,
  SiNodedotjs,
  SiOpenai,
  SiPandas,
  SiPostgresql,
  SiPrefect,
  SiPython,
  SiReact,
  SiSqlite,
  SiSwagger,
  SiTypescript,
} from "react-icons/si";

export const TECH_ICON_MAP: Record<string, IconType> = {
  "Python": SiPython,
  "PostgreSQL": SiPostgresql,
  "Prefect": SiPrefect,
  "FastAPI": SiFastapi,
  "Docker": SiDocker,
  "Docker Compose": SiDocker,
  "SQLAlchemy": SiSqlalchemy,
  "Pydantic": SiPydantic,
  "pytest": SiPytest,
  "JWT": SiJsonwebtokens,
  "Pandas": SiPandas,
  "OpenAI API": SiOpenai,
  "Gemini API": SiGooglegemini,
  "Jupyter": SiJupyter,
  "React Native": SiReact,
  "React Navigation": SiReact,
  "React Hook Form": SiReact,
  "Expo": SiExpo,
  "Expo Sensors": SiExpo,
  "TypeScript": SiTypescript,
  "MobX": SiMobx,
  "Axios": SiAxios,
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  "SQLite3": SiSqlite,
  "Swagger/OpenAPI": SiSwagger,
  "Mocha": SiMocha,
};
